import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>WillRosen - Inicio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <h1 className="heading">Desde el inicio</h1>
    <Link href="/about">Nosotros</Link>
    </div>
  )
}
